CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'data_entry',
  pin_hash TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS clients (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  balance NUMERIC NOT NULL DEFAULT 0,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS plate_numbers (
  id SERIAL PRIMARY KEY,
  plate TEXT NOT NULL UNIQUE,
  default_rate NUMERIC NOT NULL DEFAULT 0,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS trips (
  id SERIAL PRIMARY KEY,
  client_id INTEGER NOT NULL REFERENCES clients(id),
  plate_id INTEGER NOT NULL REFERENCES plate_numbers(id),
  trip_number INTEGER NOT NULL,
  invoice_number TEXT NOT NULL UNIQUE,
  trip_date TEXT NOT NULL,
  trip_time TEXT NOT NULL,
  item TEXT NOT NULL DEFAULT 'Clean Water',
  amount NUMERIC NOT NULL DEFAULT 0,
  payment_status TEXT NOT NULL DEFAULT 'Unpaid',
  note TEXT,
  deposit_used NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payments (
  id SERIAL PRIMARY KEY,
  client_id INTEGER NOT NULL REFERENCES clients(id),
  amount NUMERIC NOT NULL,
  payment_date TEXT NOT NULL,
  note TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS deposits (
  id SERIAL PRIMARY KEY,
  client_id INTEGER NOT NULL REFERENCES clients(id),
  amount NUMERIC NOT NULL,
  remaining NUMERIC NOT NULL,
  deposit_date TEXT NOT NULL,
  note TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS settings (
  id SERIAL PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  value TEXT,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS audit_log (
  id SERIAL PRIMARY KEY,
  user_id INTEGER,
  action TEXT NOT NULL,
  details TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO settings (key, value) VALUES
  ('company_name', 'Dhiblawe WaterFlow'),
  ('company_logo', ''),
  ('company_phone', '+254 700 000 000'),
  ('invoice_prefix', 'DWF-'),
  ('report_title', 'Water Delivery Report'),
  ('report_footer', 'System Generated by Dhiblawe WaterFlow Operations System'),
  ('report_prepared_by', 'Burhaan | Financial Reporting Officer | Nairobi, Kenya'),
  ('report_footer_message', 'Please settle your outstanding balance at your earliest convenience.')
ON CONFLICT (key) DO NOTHING;
